name: Docker Image Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted    #ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build-Push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/rock-paper-scissors:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          path: 